name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Buildozer dan Cython
        run: |
          python3 -m pip install --user --break-system-packages buildozer cython

      - name: Cek Buildozer dan Cython
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          buildozer --version
          cython --version

      - name: Build APK
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export ANDROID_HOME="/usr/local/lib/android/sdk"
          export ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"
          export ANDROID_NDK="/usr/local/lib/android/sdk/ndk/27.3.13750724"

          buildozer android debug

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: angka-random-apk
          path: bin/*.apk
