name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Buildozer dan Cython
        run: |
          python3 -m pip install --user --break-system-packages buildozer cython

      - name: Siapkan Android SDK untuk Buildozer
        run: |
          export ANDROID_HOME="/usr/local/lib/android/sdk"
          export ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"

          echo "ANDROID_HOME=$ANDROID_HOME"

          echo "Cek Android SDK:"
          ls -la "$ANDROID_HOME"

          echo "Cek cmdline-tools:"
          ls -la "$ANDROID_HOME/cmdline-tools" || true

          echo "Cek sdkmanager:"
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --version

          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true

      - name: Build APK
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export ANDROID_HOME="/usr/local/lib/android/sdk"
          export ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"

          buildozer android debug

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: angka-random-apk
          path: bin/*.apk
